name: Generate Snake

on:
  schedule:
    # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Gera a animação
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Luc2789
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Publica no branch "output"
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

